[theme]
font = "Montserrat:https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
baseFontSize = 17
dataframeHeaderBackgroundColor = "#95B7FF"
dataframeBorderColor = "#584f56"
primaryColor = "#142d61"